site_name: CSNote

theme:
  name: material
  features:
    - content.code.select
    - content.code.copy
    - content.code.cop
    - navigation.tabs
    - navigation.top

    # - navigation.prune
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
  custom_dir: overrides

repo_url: https://github.com/Nopthon/csnotes

repo_name: CSNote repo

plugins:
  - mermaid2
  - statistics
  - glightbox
  - document-dates:
      position: bottom # top
      type: date
      # exclude:
      date_format: '%Y-%m-%d'
      time_format: '%H:%M:%S'
      show_author: false
#  - privacy

#   - blog

nav: 
  - intro: index.md
  - OI-learning: 
    - intro: OI-Learning/index.md
    - C++ 面向对象: OI-Learning/C++ OOP.md

    - Algorithm: 
      - STL 算法库 ref: OI-Learning/Algorithm/STL_algorithm.md
      - 快速幂: OI-Learning/Algorithm/fastpow.md

    - Data Structure:
      - Trees:
        - 树基础: OI-Learning/Data-Structure/Tree/tree-intro.md
        - 二叉树基础: OI-Learning/Data-Structure/Tree/binatree.md
        - 二叉树模板: OI-Learning/Data-Structure/Tree/binatree-template.md
      - Graphs:
        - 并查集: OI-Learning/Data-Structure/Graph/union-find.md
      - 链表: OI-Learning/Data-Structure/linkedlist.md
      - STL vector ref: OI-Learning/Data-Structure/vector.md
      - 栈 && 单调栈: OI-Learning/Data-Structure/stack.md
      - 队列 && 单调队列: OI-Learning/Data-Structure/queue.md
      - 散列表/哈希表: OI-Learning/Data-Structure/hashmap.md
    
  - Course Notes:
    - intro: course-notes/index.md
    - ICSPA x86 note: 
      - README FIRST: course-notes/ICSPA-x86/README.md
      - Closed temporaily: 404.md
      # - PA0: course-notes/ICSPA-x86/PA0.md
      # - PA1: course-notes/ICSPA-x86/PA1.md
      # - PA2-1: course-notes/ICSPA-x86/PA2-1.md
      # - i386 指令结构 for PA2-1: course-notes/ICSPA-x86/i386.md
      # - PA2-2: course-notes/ICSPA-x86/PA2-2.md
      # - PA2-3: course-notes/ICSPA-x86/PA2-3.md
      # - Before PA3&&4: course-notes/ICSPA-x86/Before_PA3_&&_4.md
      # - PA3-1: course-notes/ICSPA-x86/PA3-1.md
      # - PA3-2: course-notes/ICSPA-x86/PA3-2.md
      # - PA3-3: course-notes/ICSPA-x86/PA3-3.md
      # - PA4-0: course-notes/ICSPA-x86/PA4-0.md
      # - PA4-1: course-notes/ICSPA-x86/PA4-1.md
      # - PA4-2: course-notes/ICSPA-x86/PA4-2.md
      # - PA4-3: course-notes/ICSPA-x86/PA4-3.md
      # - A journey of debugging: course-notes/ICSPA-x86/A_journey_of_debug.md

    - 网络攻防实战 Labs:
      - intro: course-notes/Network-attack-and-defense-in-action/index.md
      - Lab01: course-notes/Network-attack-and-defense-in-action/lab01.md
      - Lab02: course-notes/Network-attack-and-defense-in-action/lab02.md
      - Lab03: course-notes/Network-attack-and-defense-in-action/lab03.md
      - Lab04: course-notes/Network-attack-and-defense-in-action/lab04.md
      - Lab05: course-notes/Network-attack-and-defense-in-action/lab05.md
      - Lab06: course-notes/Network-attack-and-defense-in-action/lab06.md
      - Lab06.5: course-notes/Network-attack-and-defense-in-action/lab06.5.md

    - ICS && CSAPP Labs:
      - intro: course-notes/ICS&&CSAPP-Lab/index.md
      - CSAPP Datalab: course-notes/ICS&&CSAPP-Lab/Datalab.md
      - CSAPP Bomblab: course-notes/ICS&&CSAPP-Lab/Bomblab.md
      - ICS Binalab: course-notes/ICS&&CSAPP-Lab/Binalab.md
      - ICS Linklab: course-notes/ICS&&CSAPP-Lab/Linklab.md
      - ICS Bufolab: course-notes/ICS&&CSAPP-Lab/Bufolab.md

    - Probability: 
      - intro: course-notes/Probability/index.md
      - speedrun: course-notes/Probability/speedrun.md
      - tip: course-notes/Probability/tip.md

    - 数据结构 OJ Ans: 
      - intro: course-notes/Data-Structure-Online-Judge-Sol/index.md
      - 第 1 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ1.md
      - 第 2 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ2.md
      - 第 3 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ3.md
      - 第 4 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ4.md
      - 第 5 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ5.md
      #- 第 1 次竞赛: course-notes/Data-Structure-Online-Judge-Sol/Exam1.md
      - 第 6 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ6.md
      - 第 7 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ7.md
      - 第 8 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ8.md
      - 第 9 次实验: course-notes/Data-Structure-Online-Judge-Sol/OJ9.md


  # - Deep Learning:
  #     - intro: Deep-Learning/intro.md
  
markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - https://fonts.loli.net/css?family=JetBrains Mono:400,500,600,700&display=swap
  - https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/lxgwwenkai-regular.css
  - https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/lxgwwenkaimono-bold.css

extra_javascript:
  - stylesheets/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js